version: "1"
services:
  postgres:
    container_name: postgres-database
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: policia_db
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
